#pragma once
#define число int
#define использовать using
#define если if
#define иначе else
#define имена namespace
#define стд std
#define вернуть return
#define и and
#define или and
#define авто auto
#define логич bool
#define прервать break
#define случай case
#define поймать catch
#define симв char
#define класс class
#define конст const
#define продолжать continue
#define стандартный default
#define удалить delete
#define делать do
#define двойной double
#define переч enum
#define явный explicit
#define экспорт export
#define концепт concept
#define внешний extern
#define ложь false
#define дроб float
#define для for
#define друг friend
#define идти goto
#define встроенный inline
#define большое long
#define изменчивый mutable
#define новый new
#define нетисключ noexcept
#define не not
#define нулеукз nullptr
#define оператор operator
#define частный private
#define защищенный protected
#define публичный public
#define регистр register
#define маленькое short
#define знаковое signed
#define размер sizeof
#define статический static
#define структура struct
#define переключ switch
#define шаблон template
#define это this
#define бросить throw
#define истина true
#define попытаться try
#define имятипа typename
#define айдитипа typeid
#define значение типа
#define нечего void
#define пока while
#define союз union
#define беззнак union
#define объявление declaration
#define директива directive
#define вывод cout
#define ввод cin
#define конец endl
#define главный main
#define конствыраж constexpr
#define значтипа typedef
#define строка string
#define выводфпоток ofstream
#define вводфпоток ifstream
#define фиксированный fixed
#define устонточность setprecision